### ISSUE TITLE
Compatibility issue with numpy version

### ISSUE THREAD

**Issue by ananv21** [RUCAIBox/UniSRec#14]
Hello,

What numpy and pandas versions should I be using with this code? Recbole v1.0.1 has a compatibility issue with using numpy > 1.20.0

Thanks!

**Comment by hyp1231** [comment]
Hi, I guess `numpy==1.19` should be fine, but if not, maybe try another one or two lower versions.

**Comment by ananv21** [comment]
> Hi, I guess `numpy==1.19` should be fine, but if not, maybe try another one or two lower versions.

I tried using numpy==1.19 as well as later versions, but I run into a compatibility issue with tensorflow (which requires numpy > 1.20). However, upgrading numpy to this version leads to a conflict with recbole==1.0.1. how can I resolve this?

**Comment by hyp1231** [comment]
I'll try to do some adaptation work today or tomorrow to make the code work fine with recbole 1.2.0 and updated versions of other popular libraries.

**Comment by hyp1231** [comment]
Hi, after [967763d](https://github.com/RUCAIBox/UniSRec/commit/967763d9f61fca0296763f85cb223ba0453e5ed2) I think this repo should work fine w/ `recbole==1.2.0` and up-to-date `numpy` versions. If any problem occurs, please don't hesitate to propose some new issues, thx!

**Comment by ananv21** [comment]
Thank you so much!!
