### ISSUE TITLE
Would you mind to provide an apache 2 license for your code?

### ISSUE THREAD

**Issue by myhakureimu** [RUCAIBox/UniSRec#2]
We wish to reproduce your results, and thus wish that you could provide a license.

**Comment by myhakureimu** [comment]
We wish to reproduce your results, and thus wish that you could provide a license.

**Comment by hyp1231** [comment]
Thanks for your attention!

By the way, would MIT license works for you too? I would try to keep the consistency between this repo and [RecBole](https://github.com/RUCAIBox/RecBole).

**Comment by myhakureimu** [comment]
Yep! The MIT license works! Thank you very much for adding it!

**Comment by hyp1231** [comment]
Done! :)

**Comment by myhakureimu** [comment]
Thank you!
