### ISSUE TITLE
关于自定义数据集最长交互序列小于50的问题

### ISSUE THREAD

**Issue by Milkyorange** [RUCAIBox/UniSRec#22]

**Comment by hyp1231** [comment]
> 复现模型时无法补齐到50

请问是说程序会报错吗？有具体的报错 log 吗？这样可以帮助定位 bug 的位置，谢谢！

**Comment by Milkyorange** [comment]
> > 复现模型时无法补齐到50
> 
> 请问是说程序会报错吗？有具体的报错 log 吗？这样可以帮助定位 bug 的位置，谢谢！
感谢您的回复！
![问题](https://github.com/user-attachments/assets/fdbadd3b-b475-4a79-b5b2-26533a887bf4)
这是我们按照您的数据集预处理文件处理另一个公开数据集后复现模型时的模型forward部分，所输出的item_seq的长度以及具体的交互序列，其不足50，我们分析了后发现是process_amazon.py中的这个部分引起的
![问题2](https://github.com/user-attachments/assets/458c6817-2e60-4129-8e3c-84cb8bf410a9)
这一部分只考虑了交互序列大于50的情况，当数据集中的交互序列不足50时，其会取数据集中的最大交互序列，这会在使用某些数据集时出现问题，麻烦您了，谢谢！
