### ISSUE TITLE
(Kind help): About the Experimental Setup for Baselines

### ISSUE THREAD

**Issue by yiyualt** [RUCAIBox/UniSRec#3]
Hi, thanks for your great work, it is an inspiring study!   

May I have some questions on how the baselines are conducted for comparison?   The baseline models could be grouped into two types: (1) sequential models on single domain (e.g., SASR, BERT4Rec, S3Rec).  (2) cross-domain based models (e.g., CCDR, RecGURU). 

While you pre-train the UniSRec model on the mixture of five source domains and then fine-tune it for **each** target domain of the five datasets, how are the above two types of baselines trained?   Are they just trained on the down-stream dataset or in the same way as UniSRec model? 

Correct me if I made any mistakes. :-)

Many thanks if you kindly provide any clues.

**Comment by hyp1231** [comment]
Hi, thanks for your attention!

Yeah, you are right! The baselines can be grouped into these two categories. For the sequential models on single domains, they are trained only on downstream datasets. For the cross-domain based models CCDR, RecGURU and ZESRec, we try to leverage the same pre-trained data as UniSRec.

**Comment by yiyualt** [comment]
Thanks for your answer, it solves my question!
