### ISSUE TITLE
Scripts for baseline methods

### ISSUE THREAD

**Issue by BoPeng112** [RUCAIBox/UniSRec#4]
Thanks for the inspiring work! I am trying to reproduce the results of baseline methods. However, the run_baseline.py only works for SASRec. Would you mind sharing the scripts for the other baseline methods?

**Comment by hyp1231** [comment]
Thanks for your interest!

---

For ID-based baselines that have been implemented In recbole 1.0.1, like BERT4Rec and those methods that are even not compared In our paper, the scripts are quite similar to SASRec:

BERT4Rec:
```
python run_baseline.py -m BERT4Rec -d Scientific --config_files=props/finetune.yaml --hidden_size=300
```

GRU4Rec:
```
python run_baseline.py -m GRU4Rec -d Scientific --config_files=props/finetune.yaml --embedding_size=300
```

---

For baselines with textual features, we slightly modify RecBole's implementations to make sure the textual features are leveraged the same as UniSRec. **We will upload the implementations and scripts soon (FDSA, S^3-Rec).** It takes time to refactor the codebase but I'll try my best to make it uploaded this or the next week.

---

For the baseline ZESRec, to the best of our knowledge, the official implementation of ZESRec has not been released, thus we prefer not to upload the corresponding code recently. But I believe that it can be implemented in an easy way. One similar implementation can be regarded as the ablation of UniSRec, by replacing the MoE-enhanced adaptor to one linear module, and removing additional pre-training tasks.

---

For the baselines CCDR and RecGURU, the reported results are based on our own implementations. As the official code of both methods have been released now (Nov. 15), we prefer to reimplement these methods and test their performances thoroughly.

---

Overall, I'll comment again once the implementations of FDSA and S^3-Rec are ready. As FDSA mostly performs the best among baselines, I hope this can help with your reproduction.

**Comment by BoPeng112** [comment]
Thank you very much for the comprehensive answer. Looking forward to the implementations! I will close the issue.

**Comment by hyp1231** [comment]
Hi @BoPeng112, we have uploaded the implementations and scripts of FDSA and S^3-Rec, please refer to https://github.com/RUCAIBox/UniSRec/issues/4#issuecomment-1316045022 for details. Thanks again for your interests!!
