### ISSUE TITLE
Question about pre-training script. 

### ISSUE THREAD

**Issue by yanglilian** [RUCAIBox/UniSRec#6]
Thanks for your great work! I ran the command of the pre-training script, but it failed because your provided pre-processed datasets did not match the file of "dataset.py" (there is no dataset file ended with ".pt_datasets"). Could you please provide the right full pre-processed datasets or change the code in "dataset.py" for pre-training? Thanks.

**Comment by hyp1231** [comment]
Hi, thanks for your interest!

I've checked the dataset released on [[Google Drive]](https://drive.google.com/drive/folders/1Uik0fMk4oquV_bS9lXTZuExAYbIDkEMW?usp=sharing). After downloading and unzipping `pretrain-datasets.zip`, and move the folder `pretrain` into `UniSRec/dataset/`, we can find the file named `UniSRec/dataset/pretrain/FHCKM/FHCKM.pt_datasets`.

Can you double-check whether the mentioned file exist?

**Comment by hyp1231** [comment]
Due to inactivity for a long time, this issue will be closed. Please feel free to reopen it if you have further questions.
