### ISSUE TITLE
can't reproduce results without changing any parameters

### ISSUE THREAD

**Issue by dobogi** [RUCAIBox/UniSRec#8]
hello, I just run the command line "python finetune.py -d Arts -p saved/UniSRec-FHCKM-300.pth --train_stage=inductive_ft" and "python finetune.py -d Arts", the results indicate the performance of the former is far worse than that of the latter, which means the pretrained model doesn't work. How to explain it?

**Comment by hyp1231** [comment]
Hi! Thanks for your attention!

First, it seems that the underlying features of the two given experiments are different. For example, **only text** for `python finetune.py -d Arts -p saved/UniSRec-FHCKM-300.pth --train_stage=inductive_ft` and **text+ID** for `python finetune.py -d Arts`. It's better to unify the used features to analyze results.

Second, although UniSRec can benefit from pre-training on all the experimental datasets in the transductive setting (text+ID), we do observe that UniSRec may suffer from negative transfer issues in the inductive setting when the downstream dataset is large (e.g., *Arts* and *Office*). In our TheWebConf'23 paper (https://arxiv.org/pdf/2210.12316), we analyze the negative transfer issues and propose a new model called VQ-Rec, which can benefit from pre-training in the inductive setting.

**Comment by dobogi** [comment]
Thank you for your prompt reply, I reproduced the result just now. I'll close the issue :D.
